name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: asdf-vm/actions/setup@v3
        with:
          asdf-version: "v0.13.1"
          tool-versions: ".tool-versions"

      - name: Cache asdf & pnpm
        uses: actions/cache@v4
        with:
          path: |
            ~/.asdf/installs
            ~/.asdf/download
            ~/.local/share/pnpm/store  # pnpm 글로벌 스토어
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions','pnpm-lock.yaml') }}

      - run: node -v

      - run: pnpm install --frozen-lockfile

      - run: pnpm lint
      - run: pnpm test --run
      - run: pnpm typecheck
